version: '3.9'

services:
  trading_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    volumes:
      - ./data:/app/DATA_OHLCV
      - ./configs:/app/configs
      - ./logs:/app/LOGS
      - ./reports:/app/REPORTS
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py --btest

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      # Отдаём те же HTML-файлы
      - ./reports:/usr/share/nginx/html:ro
      - ./templates:/usr/share/nginx/html/templates:ro
      # (опционально) кастомный конфиг Nginx
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - trading_bot
