version: '3.8'

services:
  trading_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py

  trading_bot_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: trading_bot_dev
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py --btest

  trading_bot_data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_data
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    command: python app.py --ldata